version: "3.9"

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}

services:
  app:
    # image: node:18.15.0
    build:
      # dockerfile: Dockerfile
      context: ./
      target: app-development
    # user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    extra_hosts: # For Linux
      - host.docker.internal:host-gateway
    tty: true
    expose:
      - 3000
    command: "npm run dev"
    volumes:
      - ./:/home/node/app

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: myDatabase
      MYSQL_ROOT_PASSWORD: super
    volumes:
      - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      # Uncomment this line to enable persistence
      # - db:/var/lib/mysql

# Uncomment these lines to enable persistence
# volumes:
#   db:
